console.group("Group 1");
console.log("m1");
console.log("m2");
console.group("Child Group");
console.log("m1");
console.log("m2");
console.group("Grand Child Group");
console.log("m1");
console.log("m2");
console.groupEnd("");
console.groupEnd("");
console.groupEnd("");
console.group("Group 2");
console.log("m1");
console.log("m2");